apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.global.agentConfigName }}
  labels:
    {{- include "litmus-agent.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "subscriber.serviceAccountName" . }}
      containers:
      - name: init-{{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: vr00mm/litmus-agent:latest
        envFrom:
          - secretRef:
              name: {{ .Values.global.agentConfigName }}-register
        env:
          - name: AGENT_NAME
            value: {{ .Values.global.config.AGENT_NAME }}
          - name: AGENT_DESCRIPTION
            value: {{ .Values.global.config.AGENT_DESCRIPTION }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
          - name: APP_VERSION
            value: {{ .Chart.AppVersion }}
          - name: CONFIG_MAP_NAME
            value: {{ .Values.global.agentConfigName }}
          - name: SERVICE_ACCOUNT_NAME
            value: {{ include "litmus-agent.serviceAccountName" . }}
          - name: RELEASE_NAME
            value: {{ .Release.Name }}
