apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.agentConfigName }}-register
  labels:
    {{- include "litmus-agent.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  LITMUS_FRONTEND_URL: {{ .Values.global.secret.LITMUS_URL | b64enc | quote }}
  LITMUS_BACKEND_URL: {{ (.Values.global.secret.LITMUS_BACKEND_URL | default (printf "%s/backend" .Values.global.secret.LITMUS_URL)) | b64enc | quote }}
  LITMUS_USERNAME: {{ .Values.global.secret.LITMUS_USERNAME | b64enc | quote }}
  LITMUS_PASSWORD: {{ .Values.global.secret.LITMUS_PASSWORD | b64enc | quote }}
  LITMUS_PROJECT_ID: {{ .Values.global.secret.LITMUS_PROJECT_ID | b64enc | quote }}
